# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  	build_number = get_build_number_repository()
    build_app(
    	scheme: "Jenkins",
    	clean: true,
		silent: true,
		export_method: "development",
		output_directory: "/Users/zhaoning/Desktop/测试包",
		output_name: "HibyMusic_beta_build_"+build_number,
			)
    # upload_to_testflight
  end
end
